### ISSUE TITLE
PetaBencana.id logo

### ISSUE THREAD

**Issue by anexact** [urbanriskmap/userdesign#1]
Please use PetaBencana.id logo as specified here; this logo has been tested by field office and approved with Indonesian partners and audience at all levels; logos with flood imagery should be discarded from design files. Please use **ONLY** Indonesian (red/white) ball as it is part of outreach videos, promotional materials, etc.
![petabencana_logo_black_large](https://cloud.githubusercontent.com/assets/20785542/20513155/b7c11b6c-b0b6-11e6-8f36-9c3826f9939c.png)
cc @talltom @mgvarley @matthewberryman

**Comment by talltom** [comment]
Ping @asbarve -> see @anexact's comments above, please can you update design guide when you get a chance and close this issue? Thanks.

**Comment by asbarve** [comment]
Changed the logo, Will upload the new document shortly.
Just to clarify This change is just applicable to the logo and We will still be using the map pin as a droplet - or similar variation on that theme.

**Comment by talltom** [comment]
Hi @asbarve - great, thanks. Yes we're still going to use map pin droplet.
